[package]
name = "transfer-rust"
version = "0.1.0"
authors = ["Wang Yuan <junxue.w@gmail.com>"]

[dependencies]
tokio-core = "*"
tokio-io = "*"
futures = "*"
serde = "*"
serde_json = "*"
serde_derive = "*"
